# Generated by Django 5.1.2 on 2024-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('input_data', models.CharField(max_length=200)),
                ('output_data', models.CharField(max_length=200)),
            ],
        ),
    ]
