# Generated by Django 5.1.2 on 2024-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0006_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_choice',
            field=models.BooleanField(default=False),
        ),
    ]
